- name: NewRelic | RedHat {{ansible_distribution_major_version}} | 1.0. Check that newrelic-infra.yml exists
  stat:
    path: /etc/newrelic-infra.yml
  register: stat_result

- name: NewRelic | RedHat {{ansible_distribution_major_version}} | 1.1. Create newrelic-infra.yml
  file:
    path: /etc/newrelic-infra.yml
    state: touch
  when: not stat_result.stat.exists

- name: NewRelic | RedHat {{ansible_distribution_major_version}} | 2. Add license key in the config file
  lineinfile:
    path: /etc/newrelic-infra.yml
    regexp: '^license_key: {{ newrelic_license_key }}'
    line: 'license_key: {{ newrelic_license_key }}'
    state: present

- name: NewRelic | RedHat {{ansible_distribution_major_version}} | 3.0 Check If repository exists
  stat:
    path: /etc/yum.repos.d/newrelic-infra.repo
  register: stat_result

- name: NewRelic | RedHat {{ansible_distribution_major_version}} | 3. Add repository repository yum
  ansible.builtin.yum_repository:
    name: newrelic-infra
    description: Repository NewRelic Infraestructure Agent
    baseurl: https://download.newrelic.com/infrastructure_agent/linux/yum/el/{{ansible_distribution_major_version}}/x86_64/
    state: present
  when: not stat_result.stat.exists

- name: NewRelic | RedHat {{ansible_distribution_major_version}} | 4. Enable repository newrelic and Install
  shell: sudo yum -q makecache -y --disablerepo='*' --enablerepo='newrelic-infra'
  become: yes
  register: install

# - name: NewRelic | RedHat {{ansible_distribution_major_version}} | 4. Enable repository newrelic and Install
#   yum:
#     name: newrelic-infra
#     update_cache: yes
#     disablerepo: '*'
#     enablerepo: newrelic-infra
#   become: yes
#   register: install

- name: NewRelic | RedHat {{ansible_distribution_major_version}} | 5. Restart service
  ansible.builtin.service:
    name: newrelic-infra
    state: restarted
  when: install.changed
