---

- name: talk to all hosts for ansible distribution and ansible distribution major
  hosts: all
  gather_facts: true
  tasks:
    - name: Classify hosts depending on their OS distribution
      group_by:
        key: "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}"

- hosts: Ubuntu_20
   gather_facts: false
   tasks:
     - name: NewRelic | Install Infraestructure Agent
       include_tasks: install_new_relic_agent_ubuntu_20.yml
