---
- hosts: all
  become: yes
  gather_facts: true

  vars:
    os_codename: focal

  tasks:
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts

    - name: NewRelic | Uninstall
      apt:
        name: newrelic-infra
        state: absent
