---
- hosts: 172.31.1.176
  become: yes
  tasks:
    - name: Copy update.sh to server
      copy:
        src: /var/lib/awx/projects/_12__linux/update.sh
        dest: /tmp/update.sh
        owner: ubuntu
        group: ubuntu
        mode: '0766'
    - name: Get a list of security updates
      command: /bin/bash /tmp/update.sh 2> /dev/null
      ignore_errors: no
    - name : List security updates
      command: cat /tmp/updates.json
      register: out
    
    - set_fact:
        string_to_echo: "{{ command_output.stdout }}"
...

