---
- hosts: all
  become: yes
  tasks:
    - name: Copy update.sh to server
      copy:
        src: /var/lib/awx/projects/_12__linux/update.sh
        dest: /tmp/update.sh
        owner: ubuntu
        group: ubuntu
        mode: '0766'
        
    - name: Get a list of security updates
      command: bash /tmp/update.sh
      ignore_errors: yes
      
    - name : List security updates
      shell: cat /tmp/updates.json
      register: out
      
    - debug: var=out.stdout
...
