---
- hosts: 172.31.1.176
  become: yes
  tasks:
    - name: Copy update.sh to server
      copy:
        src: /var/lib/awx/projects/_12__linux/update.sh
        dest: /tmp/update.sh
        owner: ubuntu
        group: ubuntu
        mode: '0766'
        no_log: True
    - name: Get a list of security updates
      command: sh /tmp/update.sh
      ignore_errors: yes
    - name : List security updates
      command: cat /tmp/update.json
      register: out
    
    - debug: var=out.stdout_lines
...

