---

- name:
  hosts: all
  gather_facts: true
  tasks:

    # UBUNTU BLOCK

    - name: NewRelic | Install Infraestructure Agent Ubuntu
      include_tasks: "./ubuntu/install_new_relic_agent_ubuntu.yml"
      when:
        - ansible_distribution_major_version in ['20', '18', '16', '14', '12']
        - ansible_distribution | lower == 'ubuntu'

    - name: NewRelic | SO Ubuntu No Contemplado
      debug:
        msg: "Version Ubuntu {{ansible_distribution_major_version}} not covered,  Ubuntu versions covered: 20 | 18 | 16 | 14 | 12
              If it is a new version contact the administrator"
      when:
        - ansible_distribution_major_version not in ['20', '18', '16', '14', '12']
        - ansible_distribution | lower == 'ubuntu'

      # REDHAT BLOCK

    - name: NewRelic | Install Infraestructure Agent RHEL 8
      include_tasks: ./redhat/install_new_relic_agent_rhel.yml
      when:
        - ansible_distribution_major_version in ['8', '7', '6']
        - ansible_distribution | lower == 'redhat'

    - name: NewRelic | SO RedHat No Contemplado
      ansible.builtin.debug:
        msg: "Version RedHat {{ansible_distribution_major_version}} not covered,  RedHat versions covered: 8 | 7 | 6
              If it is a new version contact the administrator"
      when:
        - ansible_distribution_major_version not in ['8', '7', '6']
        - ansible_distribution | lower == 'redhat'
