---

- name:
  hosts: all
  gather_facts: true
  tasks:

    # UBUNTU BLOCK

    - name: NewRelic | Install Infraestructure Agent Ubuntu
      include_tasks: "./ubuntu/install_new_relic_agent_ubuntu.yml"
      when: (ansible_distribution == "Ubuntu" and
            (ansible_distribution_major_version == "16" or
             ansible_distribution_major_version == "18" or
             ansible_distribution_major_version == "20" or
             ansible_distribution_major_version == "14" or
             ansible_distribution_major_version == "12"))


    - name: NewRelic | SO Ubuntu No Contemplado
      ansible.builtin.debug:
        msg: "SO no contemplado, Distribuciones Ubuntu aceptadas: 12,14,16,18,20; {{ansible_facts['distribution_major_version']}}"
      when:  (ansible_distribution == "Ubuntu" and ansible_distribution_major_version != "18")

      # # REDHAT BLOCK

    - name: NewRelic | Install Infraestructure Agent RHEL 8
      include_tasks: install_new_relic_agent_rhel_8.yml
      when: (ansible_distribution == "RedHat" and ansible_distribution_major_version == "8" )

    - name: NewRelic | Install Infraestructure Agent RHEL 7
      include_tasks: install_new_relic_agent_rhel_7.yml
      when: (ansible_distribution == "RedHat" and ansible_distribution_major_version == "7" )

    - name: NewRelic | Install Infraestructure Agent RHEL 6
      include_tasks: install_new_relic_agent_rhel_6.yml
      when: (ansible_distribution == "RedHat" and ansible_distribution_major_version == "6" )

    - name: NewRelic | SO RedHat No Contemplado
      ansible.builtin.debug:
        msg: "SO RedHat {{ansible_distribution_major_version}} no contemplada, Distribuciones RedHat aceptadas: 5,6,7"
      when: (ansible_distribution == "RedHat" and
            (ansible_distribution_major_version != "6" or
             ansible_distribution_major_version != "7" or
             ansible_distribution_major_version != "8"))
