---

- name:
  hosts: all
  gather_facts: false
  tasks:

    # WINDOWS BLOCK

    - name: NewRelic | Install Infraestructure Windows Agent | 1.0 Check New Relic Service is alredy present
      win_service:
        name: newrelic-infra
      register: service_existence

    - name: NewRelic | Install Infraestructure Windows Agent | Information
      debug:
        msg:
          - "Actually New Relic Infraestructure Agent is alredy Installed"
          - "If is not the latest version of agent, then Uninstall and Re-Install the latest agent of newrelic"
      when: service_existence.state is defined

    - name: NewRelic | Install Infraestructure Windows Agent | 1. Set License New Relic environment variable
      win_environment:
        state: present
        name: LICENSE_NEW_RELIC_KEY
        value: '{{ newrelic_license_key }}'
        level: machine
      when: service_existence.state is not defined

    - name:  NewRelic | Install Infraestructure Windows Agent | 2. Get MSI New Relic Agent
      win_get_url:
        url: https://download.newrelic.com/infrastructure_agent/windows/newrelic-infra.msi
        dest: C:\Windows\temp\newrelic-infra.msi
      register: newrelic_get_status
      when: service_existence.state is not defined

    - name: NewRelic | Install Infraestructure Windows Agent | 3. Install Agent MSI
      win_shell: msiexec.exe /qn /i  C:\Windows\temp\newrelic-infra.msi GENERATE_CONFIG=true LICENSE_KEY='{{ newrelic_license_key }}'
      when: service_existence.state is not defined

    # - name: NewRelic | Install Infraestructure Windows Agent | 3. Install Agent MSI
    #   win_package:
    #     path: C:\Windows\temp\newrelic-infra.msi
    #     state: present
    #     arguments: GENERATE_CONFIG=true LICENSE_NEW_RELIC_KEY='{{ newrelic_license_key }}'
    #   register: nr_agent_installed
    #   when: service_existence.state is not defined

    - name: NewRelic | Install Infraestructure Windows Agent | 4. Start Agent MSI
      win_service:
        name: newrelic-infra
        state: started
      when: service_existence.state is not defined
