---
- hosts: all
  gather_facts: false

  tasks:

    # WINDOWS BLOCK

    - name: NewRelic | Uninstall Infraestructure Agent Windows | 1. Stop Infraestructure Agent
      ansible.windows.win_service:
        name: newrelic-infra
        state: status
      register: statusnr


    # - name: NewRelic | Uninstall Infraestructure Agent Windows | 2. Remove Program NewRelic
    #   win_service:
    #     name: newrelic-infra
    #     state: absent
