---
  
- name:
  hosts: all
  gather_facts: false
  tasks:

    # WINDOWS BLOCK

    - name: NewRelic | Uninstall Infraestructure Agent Windows | 1. Stop Infraestructure Agent
      win_package:
        path: C:\Windows\temp\newrelic-infra.msi
        state: absent
