---
- hosts: all
  become: yes
  gather_facts: true

  tasks:

    - name: NewRelic | Uninstall
      apt:
        name: newrelic-infra
        state: absent

    # UBUNTU BLOCK

    - name: NewRelic | Clean pending files associated with NewRelic
      file:
        path: /etc/newrelic*
        state: absent
      when:
        - ansible_distribution_major_version in ['20', '18', '16', '14', '12']
        - ansible_distribution | lower == 'ubuntu'
