---

- name:
  hosts: all
  gather_facts: false
  tasks:

    # WINDOWS BLOCK

    - name: NewRelic | Uninstall Infraestructure Windows Agent | 1.0 Check if New Relic Service Exists
      win_service:
        name: newrelic-infra
      register: defined

    - name: NewRelic | Uninstall Infraestructure Windows Agent | 1. Stop Agent MSI
      win_service:
        name: newrelic-infra
        state: stopped
      when: defined.state is defined

    - name: NewRelic | Uninstall Infraestructure Agent Windows| 2. Uninstall New Relic Service
      win_shell: (Get-WmiObject -Class Win32_Product | Where-Object{$_.Name -eq "New Relic Infrastructure Agent"}).Uninstall()
      when: defined.state is defined

    - name: NewRelic | Uninstall Infraestructure Agent Windows| 3.0 Check if New Relic MSI exists
      win_file:
        path: C:\Windows\temp\newrelic-infra.msi
      register: nrmsi

    - name: NewRelic | Uninstall Infraestructure Agent Windows| 3. Remove New Relic MSI
      win_file:
        path: C:\Windows\temp\newrelic-infra.msi
      when: nrmsi.stat.exists == True

    - name: NewRelic | Uninstall Infraestructure Agent Windows| 4. Remove MSI package if Exists
      win_environment:
        state: absent
        name: LICENSE_NEW_RELIC_KEY
        value: '{{ newrelic_license_key }}'
        level: machine
