---

- name:
  hosts: all
  gather_facts: false
  tasks:

    # WINDOWS BLOCK

    - name: NewRelic | Install Infraestructure Windows Agent | 1. Stop Agent MSI
      win_shell: net stop newrelic-infra

    - name: NewRelic | Uninstall Infraestructure Agent Windows| 1. Uninstall New Relic Program
      win_service:
        name: newrelic-infra
        state: absent
