---
- hosts: all
  become: yes
  gather_facts: false
  tasks:

    # WINDOWS BLOCK

    - name: NewRelic | Uninstall Infraestructure Agent Windows | 1. Stop Infraestructure Agent
      win_service:
        name: newrelic-infra
        state: stopped

    - name: NewRelic | Uninstall Infraestructure Agent Windows | 2. Remove Program NewRelic
      win_service:
        name: newrelic-infra
        state:absent
