---
- hosts: all
  become: yes
  gather_facts: true
  #vars:
  #  ubuntu_paths: ['/etc/', '/etc/systemd/system/']
  tasks:

    - name: NewRelic | Uninstall
      apt:
        name: newrelic-infra
        state: absent

    # UBUNTU BLOCK

    - name: NewRelic | Clean pending files associated with NewRelic
      file:
        path: /etc
        state: absent
      when:
        - ansible_distribution_major_version in ['20', '18', '16', '14', '12']
        - ansible_distribution | lower == 'ubuntu'
