---
- hosts: all
  become: yes
  gather_facts: true

  tasks:

    - name: NewRelic | Uninstall
      apt:
        name: newrelic-infra
        state: absent

    # UBUNTU BLOCK

    - name: NewRelic | Find pending files associated with NewRelic on /etc
      find:
        path: '/etc'
        pattern: "^newrelic*$"
        recurse: yes
        file_type: file
      register: files_etc

    - name: NewRelic | Find pending files associated with NewRelic on /var
      find:
        path: '/var'
        pattern: "^newrelic*$"
        recurse: yes
        file_type: file
      register: files_var

    - name: NewRelic | Remove pending files
      file:
        path: '{{ item.path }}'
        state: absent
      with_items:
        - '{{ files_etc.files }}'
        - '{{ files_var.files }}'




    # - name: NewRelic | Clean pending files associated with NewRelic
    #   file:
    #     path: '{{ item }}'
    #     state: absent
    #   with_items:
    #     - /var/lib/dpkg/info/newrelic-infra.list
    #     - /var/lib/dpkg/info/newrelic-infra.postrm
    #     - /var/db/newrelic-infra
    #     - /var/cache/apt/archives/newrelic-infra*.deb
    #     - /etc/newrelic-infra.yml
    #     - /etc/systemd/system/newrelic-infra.service
    #     - /etc/newrelic-infra
    #   when:
    #     - ansible_distribution_major_version in ['20', '18', '16', '14', '12']
    #     - ansible_distribution | lower == 'ubuntu'
