---

- name:
  hosts: all
  gather_facts: false
  tasks:

    # WINDOWS BLOCK

    - name: NewRelic | Uninstall Infraestructure Windows Agent | 1.0 Check if New Relic Service Exists
      win_service:
        name: newrelic-infra
        register: defined

    - name: NewRelic | Uninstall Infraestructure Windows Agent | 1. Stop Agent MSI
      win_service:
        name: newrelic-infra
        state: stopped
      when: defined.state is defined

    - name: NewRelic | Uninstall Infraestructure Agent Windows| 1. Uninstall New Relic Program
      win_service:
        name: newrelic-infra
        state: absent
      when: defined.state is defined
